testNG2_homework1
AlekseiSapach/QA21SapachAleksei pull request #1
Opened 2023-06-24 13:03 UTC by AlekseiSapach

2023-06-26 15:15 UTC, wildpioneer requested changes

2023-06-26 15:15 UTC, wildpioneer commented on src/main/java/Calculator.java
> +    public int divInt(int a, int b)
Почему названия методов разные?
Повторить перегрузку методов

2023-06-26 15:15 UTC, wildpioneer commented on src/test/java/HomeWorkTest.java
> +    public void testDivDoubleZero(double a, double b, double expectedValue)
Отсутствуют следующие тесты:

1. enable
2. description
3. invocationCount, invocationTimeOut, threadPoolSize
4. timeOut
5. dependsOnMethods
6. @Parameters
7. priority
8. retryAnalyzer
9. Double.NaN
10. Double.NEGATIVE_INFINITY
11. Double.POSITIVE_INFINITY

2023-06-26 15:27 UTC, AlekseiSapach commented on src/test/java/HomeWorkTest.java
> +    public void testDivDoubleZero(double a, double b, double expectedValue)
Что такое пункт 6? По поводу 9 -11 тоже не понял, я же проверяю эти моменты
И по поводу остальных пунктов сейчас дополню

2023-06-26 15:32 UTC, AlekseiSapach commented on src/test/java/HomeWorkTest.java
> +    public void testDivDoubleZero(double a, double b, double expectedValue)
И по поводу параметров с 1 - 5, 7, 8 мне нужно их добавить в мои имеющиеся 4 теста?

2023-06-26 15:32 UTC, AlekseiSapach commented on src/main/java/Calculator.java
> +    public int divInt(int a, int b)
Понял, поправлю

2023-06-26 21:18 UTC, AlekseiSapach commented
По замечаниям я всё поправил и доделал. Но случилось не поправимое, мне пришлось заново восстанавливать локально ветку с домашкой, копируя с гитхаба код((  видимо, я когда создавал ветку сегодня для классной работы, что-то сделал не так (хотя всё как всегда делал - новая ветка с предыдущей классной работы) и моя классная работа запушилась в созданную мной новую ветку ( что нормально) и внесла изменения в ветку с домашней работой (что не нормально). В итоге я удалил полностью ветку с классной из гитхаба (локально тоже), но java файл SmokeTest (из классной) всё равно отображается при пуше правок по предыдущей дз. Как его убрать? И что я мог такого нажать или сделать, что у меня так получилось?

2023-06-30 22:07 UTC, AlekseiSapach commented
С проблемой, которую озвучил в комментарии выше разобрался, теперь всё так как и должно быть

2023-07-08 19:28 UTC, wildpioneer commented
Проверено

2023-07-08 19:28 UTC, closed without merging