selenium_wd_HomeWork
AlekseiSapach/QA21SapachAleksei pull request #2
Opened 2023-07-01 22:17 UTC by AlekseiSapach

2023-07-08 19:26 UTC, wildpioneer requested changes

2023-07-08 19:26 UTC, wildpioneer commented on src/test/java/HomeWorkTest.java
> +    //Дополнительное задание: Попробовал сделать, но не получилось инициализироввать чек-бокс, в окне
Капча не обрабатывается Selenium никак - а следовательно надо поставить паузу и принять ее руками

2023-07-15 09:37 UTC, AlekseiSapach commented on src/test/java/HomeWorkTest.java
> +    //Дополнительное задание: Попробовал сделать, но не получилось инициализироввать чек-бокс, в окне
Спасибо, понял

2023-07-17 08:48 UTC, wildpioneer commented
Проверено

2023-07-17 08:48 UTC, closed without merging