pageObject_hw
AlekseiSapach/QA21SapachAleksei pull request #4
Opened 2023-07-21 23:05 UTC by AlekseiSapach

2023-07-23 14:35 UTC, wildpioneer requested changes

2023-07-23 14:35 UTC, wildpioneer commented on src/test/java/tests/End2EndTest.java
> +        Assert.assertEquals(completePage.getLabel().getText(),"Thank you for your order!");
Проверка в тесте должна быть одна - в конце - каждый шаг не надо проверять

2023-07-23 14:35 UTC, wildpioneer commented on src/test/java/tests/End2EndTest.java
> +        YouCardPage youCardPage = new YouCardPage(driver);
Инициализации этих страниц лучше вынести в BaseTest

2023-07-23 14:35 UTC, wildpioneer commented on src/test/resources/config.properties
> +username=standard_user
В папке resources отсутствует Readme.md с описанием теста

2023-07-24 15:55 UTC, AlekseiSapach commented on src/test/resources/config.properties
> +username=standard_user
так вроде общем каталоге проекта надо было?! сейчас перенесу в ресурсы

2023-07-24 15:55 UTC, AlekseiSapach commented on src/test/java/tests/End2EndTest.java
> +        YouCardPage youCardPage = new YouCardPage(driver);
понял, поправлю

2023-07-24 15:55 UTC, AlekseiSapach commented on src/test/java/tests/End2EndTest.java
> +        Assert.assertEquals(completePage.getLabel().getText(),"Thank you for your order!");
понял, поправлю

2023-07-24 16:02 UTC, AlekseiSapach commented
Все замечания исправил

2023-08-28 11:29 UTC, wildpioneer commented
Проверено

2023-08-28 11:29 UTC, closed without merging