advancedActions_hw
AlekseiSapach/QA21SapachAleksei pull request #5
Opened 2023-07-22 16:20 UTC by AlekseiSapach

2023-07-22 16:23 UTC, AlekseiSapach commented
не успеваю сегодня сделать чтобы всё работало, доделаю в воскресенье вечером, если можно

2023-07-23 14:48 UTC, wildpioneer requested changes

2023-07-23 14:48 UTC, wildpioneer commented on src/test/java/steps/LoginStep.java
>          return dashboardPage;
Забыл изменить данный класс - из-за него у меня ничего не запускается

2023-07-23 14:48 UTC, wildpioneer commented on src/test/java/tests/DynamicControlsTest.java
> +        //а тут проверяем, что его нет - противоречие получается между waitForExists и waitForElementInvisible
Чтобы понять суть проблемы - нужно научиться дебажить - если бы ты это сделал - то понял бы суть проблемы. А заключается она в следующем: твой метод dynamicControlsPage.getMessage().isDisplayed() - дожидается появления текста, но когда текст появляется - то чекбокса уже нет на экране и в DOM модели. И поэтому при попытке его найти, чтобы дождаться когда же он исчезнет - его уже нет

2023-07-23 14:48 UTC, wildpioneer commented on src/test/java/tests/DynamicControlsTest.java
> +
Форматирование - пустые строки здесь зачем?

2023-07-23 14:48 UTC, wildpioneer commented on src/test/java/tests/DynamicControlsTest.java
> +        Assert.assertFalse(Boolean.parseBoolean(dynamicControlsPage.getInputText().getAttribute("disabled")));
Проверка в тесте должна быть одна - в конце - каждый шаг не надо проверять

2023-07-23 14:48 UTC, wildpioneer commented on src/test/java/tests/FramesTest.java
> +        framesPage.openPageByUrl();
org.openqa.selenium.TimeoutException: Expected condition failed: waiting for presence of element located by: By.linkText: /iframe (tried for 10 second(s) with 500 milliseconds interval)

2023-07-28 20:29 UTC, AlekseiSapach commented on src/test/java/steps/LoginStep.java
>          return dashboardPage;
поправил

2023-07-28 21:07 UTC, AlekseiSapach commented on src/test/java/tests/DynamicControlsTest.java
> +        Assert.assertFalse(Boolean.parseBoolean(dynamicControlsPage.getInputText().getAttribute("disabled")));
поправил

2023-07-28 21:34 UTC, AlekseiSapach commented on src/test/java/tests/DynamicControlsTest.java
> +        //а тут проверяем, что его нет - противоречие получается между waitForExists и waitForElementInvisible
Спасибо, разобрался и исправил

2023-07-28 21:38 UTC, AlekseiSapach commented on src/test/java/tests/DynamicControlsTest.java
> +
пустые строки убрал

2023-07-28 21:58 UTC, AlekseiSapach commented on src/test/java/tests/FramesTest.java
> +        framesPage.openPageByUrl();
исправил

2023-07-28 21:59 UTC, AlekseiSapach commented
По всем замечаниям разобрался, правки внёс

2023-08-02 08:54 UTC, wildpioneer commented
Проверено

2023-08-02 08:54 UTC, closed without merging